### ISSUE TITLE
Application crashes if no connection.

### ISSUE THREAD

**Issue by mrmixer** [mmozeiko/ScreenBuddy#1]
When I launch ScreenBuddy the first time, my firewall blocks the connection until I authorize it. This causes a crash in `Buddy_GetBestDerpRegionThread`. VisualStudio says that `Regions` is null, but Json is too.

![screenbuddy](https://github.com/user-attachments/assets/233e49db-615f-4591-bf30-20e0e2ecf2d8)

I know this program needs a connection to work, but it just is a bad user experience. I would expect the application to still run, and letting me click the refresh button to retry the connection once I allowed the application in my firewall. I suppose it would also be the same if for some other reason the internet connection isn't present.

If I compile a debug build, `Buddy_DownloadDerpMap` in `Buddy_GetBestDerpRegionThread` returns an empty buffer with `BufferSize` equal to zero. Passing that to `JsonObject_Parse` will cause the assert `Assert(WideLength != 0);` to trigger.

**Comment by mmozeiko** [comment]
Thanks for the report. I've updated code to not crash on this. Clicking Generate New Code code will retry the whole process if previous query to derpmap failed.

In general the code in current situation is not well tested to handle errors very reliably. I'm sure there are few more places where extra fixes are needed for networking issues.

**Comment by mrmixer** [comment]
The fix works. Thanks.
